name: bestie_config_use_case
description: Config feature use case + presentation schema (entries, sections, pages).
version: 0.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  config_protocol:
    path: ../../infra/config_protocol
  config_repository:
    path: ../../domain/config_repository
  intentions: ^0.1.0
  meta: ^1.18.0

dev_dependencies:
  bestie_config:
    path: ../../data/bestie_config
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
