// Generates build/THIRD_PARTY_LICENSES.txt by gathering the full LICENSE
// text for every dependency that actually ships inside a Bestie release
// archive — Dart packages (via pub cache) and the static native-library
// texts in assets/third_party_licenses/.
//
// Run from the repo root:
//   dart tool/build_licenses.dart

import 'dart:io';

import 'src/helpers.dart';
import 'src/shipped_packages.dart';

const _appPackage = 'packages/bestie';
const _staticLicensesDir = 'assets/third_party_licenses';

Future<void> main() async {
  final root = repoRoot().path;
  final missing = <String>[];
  final sections = <_Section>[];

  sections.addAll(await _collectDartSections(root, missing));
  sections.addAll(_collectStaticSections(root));

  sections.sort((a, b) {
    final byCategory = a.category.index.compareTo(b.category.index);
    if (byCategory != 0) return byCategory;
    return a.title.toLowerCase().compareTo(b.title.toLowerCase());
  });

  final out = File('$root/build/THIRD_PARTY_LICENSES.txt');
  out.parent.createSync(recursive: true);
  out.writeAsStringSync(_render(sections));

  stdout.writeln(
    'Wrote ${out.path} '
    '(${sections.length} sections, ${out.lengthSync()} bytes)',
  );

  if (missing.isNotEmpty) {
    stderr
      ..writeln()
      ..writeln('WARNING: no LICENSE file located for:');
    for (final m in missing) {
      stderr.writeln('  - $m');
    }
    exitCode = 1;
  }
}

// ---------------------------------------------------------------------------

enum _Category { dart, native }

class _Section {
  _Section({
    required this.category,
    required this.title,
    required this.subtitle,
    required this.text,
  });

  final _Category category;
  final String title;
  final String subtitle;
  final String text;
}

String _render(List<_Section> sections) {
  final buf = StringBuffer()
    ..writeln('Bestie — Third-Party License Notices')
    ..writeln('=' * 78)
    ..writeln()
    ..writeln(
      'This file aggregates the verbatim LICENSE (and where present, NOTICE)\n'
      "text of every third-party component that ships inside this Bestie\n"
      'release archive — the Dart CLI binary and its transitive runtime\n'
      'packages, the bundled native library (curl-impersonate),\n'
      'the spawner PTY helper, the Windows console host (conpty.dll and\n'
      'OpenConsole.exe), and the statically linked Rust sidecars (brush,\n'
      'uutils coreutils, ripgrep, uutils findutils, uutils sed, and the\n'
      'bestie_edit editor) together with every crate they link.\n',
    )
    ..writeln('See CREDITS.md for a higher-level summary of who wrote what.\n')
    ..writeln('Generated by tool/build_licenses.dart.\n');

  for (final s in sections) {
    buf
      ..writeln()
      ..writeln('-' * 78)
      ..writeln(s.title)
      ..writeln(s.subtitle)
      ..writeln('-' * 78)
      ..writeln()
      ..writeln(s.text.trimRight())
      ..writeln();
  }

  return buf.toString();
}

// ---------------------------------------------------------------------------
// Dart packages
// ---------------------------------------------------------------------------

Future<List<_Section>> _collectDartSections(
  String root,
  List<String> missing,
) async {
  final shipped = await resolveShippedDartPackages(
    repoRoot: root,
    appPackagePath: '$root/$_appPackage',
    missing: missing,
  );

  final sections = <_Section>[];
  for (final pkg in shipped) {
    final license = pkg.licenseFile;
    if (license == null) {
      missing.add('${pkg.name} @ ${pkg.baseDir}');
      continue;
    }

    final notice = pkg.noticeFile;
    final text = StringBuffer(license.readAsStringSync().trimRight());
    if (notice != null) {
      text
        ..writeln()
        ..writeln()
        ..writeln('--- NOTICE ---')
        ..writeln()
        ..write(notice.readAsStringSync().trimRight());
    }

    sections.add(
      _Section(
        category: _Category.dart,
        title: pkg.name,
        subtitle: 'Dart package · version ${pkg.version} · ${pkg.source}',
        text: text.toString(),
      ),
    );
  }

  return sections;
}

List<_Section> _collectStaticSections(String root) {
  final dir = Directory('$root/$_staticLicensesDir');
  if (!dir.existsSync()) return const [];
  final sections = <_Section>[];
  for (final entity in dir.listSync()) {
    if (entity is! File) continue;
    if (!entity.path.endsWith('.txt')) continue;
    final name = entity.uri.pathSegments.last.replaceAll('.txt', '');
    sections.add(
      _Section(
        category: _Category.native,
        title: name,
        subtitle: 'Third-party component',
        text: entity.readAsStringSync().trimRight(),
      ),
    );
  }
  return sections;
}
