name: sandbox
description: >-
  bestie's cross-platform sandbox contract.
version: 0.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  dart_mappable: ^4.3.0
  file: ^7.0.1
  path: ^1.9.1
  process_host:
    path: ../process_host

dev_dependencies:
  build_runner: ^2.4.12
  dart_mappable_builder: ^4.3.0
  mocktail: ^1.0.5
  test: ^1.26.3
  very_good_analysis: ^10.0.0
