// ignore_for_file: non_constant_identifier_names
// ignore_for_file: camel_case_types
// ignore_for_file: public_member_api_docs
// ignore_for_file: constant_identifier_names
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: type=lint
//
// GENERATED by ffigen — do not edit by hand.
// See tool/ffigen_linux.yaml to change what's generated.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// POSIX (libc) + Linux bindings generated by ffigen against
/// `/usr/include`. Regenerate via `dart run melos run ffigen_posix_linux`
/// on a Linux host.
///
class LinuxPosixBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LinuxPosixBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  LinuxPosixBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int posix_spawn(
    ffi.Pointer<ffi.Int> __pid,
    ffi.Pointer<ffi.Char> __path,
    ffi.Pointer<posix_spawn_file_actions_t> __file_actions,
    ffi.Pointer<posix_spawnattr_t> __attrp,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __argv,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __envp,
  ) {
    return _posix_spawn(
      __pid,
      __path,
      __file_actions,
      __attrp,
      __argv,
      __envp,
    );
  }

  late final _posix_spawnPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<posix_spawn_file_actions_t>,
            ffi.Pointer<posix_spawnattr_t>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('posix_spawn');
  late final _posix_spawn = _posix_spawnPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<posix_spawn_file_actions_t>,
          ffi.Pointer<posix_spawnattr_t>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
        )
      >();

  int posix_spawnp(
    ffi.Pointer<ffi.Int> __pid,
    ffi.Pointer<ffi.Char> __file,
    ffi.Pointer<posix_spawn_file_actions_t> __file_actions,
    ffi.Pointer<posix_spawnattr_t> __attrp,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __argv,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __envp,
  ) {
    return _posix_spawnp(
      __pid,
      __file,
      __file_actions,
      __attrp,
      __argv,
      __envp,
    );
  }

  late final _posix_spawnpPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<posix_spawn_file_actions_t>,
            ffi.Pointer<posix_spawnattr_t>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('posix_spawnp');
  late final _posix_spawnp = _posix_spawnpPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<posix_spawn_file_actions_t>,
          ffi.Pointer<posix_spawnattr_t>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
        )
      >();

  int posix_spawnattr_init(
    ffi.Pointer<posix_spawnattr_t> __attr,
  ) {
    return _posix_spawnattr_init(
      __attr,
    );
  }

  late final _posix_spawnattr_initPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<posix_spawnattr_t>)>
      >('posix_spawnattr_init');
  late final _posix_spawnattr_init = _posix_spawnattr_initPtr
      .asFunction<int Function(ffi.Pointer<posix_spawnattr_t>)>();

  int posix_spawnattr_destroy(
    ffi.Pointer<posix_spawnattr_t> __attr,
  ) {
    return _posix_spawnattr_destroy(
      __attr,
    );
  }

  late final _posix_spawnattr_destroyPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<posix_spawnattr_t>)>
      >('posix_spawnattr_destroy');
  late final _posix_spawnattr_destroy = _posix_spawnattr_destroyPtr
      .asFunction<int Function(ffi.Pointer<posix_spawnattr_t>)>();

  int posix_spawn_file_actions_init(
    ffi.Pointer<posix_spawn_file_actions_t> __file_actions,
  ) {
    return _posix_spawn_file_actions_init(
      __file_actions,
    );
  }

  late final _posix_spawn_file_actions_initPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<posix_spawn_file_actions_t>)
        >
      >('posix_spawn_file_actions_init');
  late final _posix_spawn_file_actions_init = _posix_spawn_file_actions_initPtr
      .asFunction<int Function(ffi.Pointer<posix_spawn_file_actions_t>)>();

  int posix_spawn_file_actions_destroy(
    ffi.Pointer<posix_spawn_file_actions_t> __file_actions,
  ) {
    return _posix_spawn_file_actions_destroy(
      __file_actions,
    );
  }

  late final _posix_spawn_file_actions_destroyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<posix_spawn_file_actions_t>)
        >
      >('posix_spawn_file_actions_destroy');
  late final _posix_spawn_file_actions_destroy =
      _posix_spawn_file_actions_destroyPtr
          .asFunction<int Function(ffi.Pointer<posix_spawn_file_actions_t>)>();

  int posix_spawn_file_actions_addclose(
    ffi.Pointer<posix_spawn_file_actions_t> __file_actions,
    int __fd,
  ) {
    return _posix_spawn_file_actions_addclose(
      __file_actions,
      __fd,
    );
  }

  late final _posix_spawn_file_actions_addclosePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<posix_spawn_file_actions_t>, ffi.Int)
        >
      >('posix_spawn_file_actions_addclose');
  late final _posix_spawn_file_actions_addclose =
      _posix_spawn_file_actions_addclosePtr
          .asFunction<
            int Function(ffi.Pointer<posix_spawn_file_actions_t>, int)
          >();

  int posix_spawn_file_actions_adddup2(
    ffi.Pointer<posix_spawn_file_actions_t> __file_actions,
    int __fd,
    int __newfd,
  ) {
    return _posix_spawn_file_actions_adddup2(
      __file_actions,
      __fd,
      __newfd,
    );
  }

  late final _posix_spawn_file_actions_adddup2Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<posix_spawn_file_actions_t>,
            ffi.Int,
            ffi.Int,
          )
        >
      >('posix_spawn_file_actions_adddup2');
  late final _posix_spawn_file_actions_adddup2 =
      _posix_spawn_file_actions_adddup2Ptr
          .asFunction<
            int Function(ffi.Pointer<posix_spawn_file_actions_t>, int, int)
          >();

  int posix_openpt(
    int __oflag,
  ) {
    return _posix_openpt(
      __oflag,
    );
  }

  late final _posix_openptPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>('posix_openpt');
  late final _posix_openpt = _posix_openptPtr.asFunction<int Function(int)>();

  int grantpt(
    int __fd,
  ) {
    return _grantpt(
      __fd,
    );
  }

  late final _grantptPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>('grantpt');
  late final _grantpt = _grantptPtr.asFunction<int Function(int)>();

  int unlockpt(
    int __fd,
  ) {
    return _unlockpt(
      __fd,
    );
  }

  late final _unlockptPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>('unlockpt');
  late final _unlockpt = _unlockptPtr.asFunction<int Function(int)>();

  ffi.Pointer<ffi.Char> ptsname(
    int __fd,
  ) {
    return _ptsname(
      __fd,
    );
  }

  late final _ptsnamePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int)>>(
        'ptsname',
      );
  late final _ptsname = _ptsnamePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  int close(
    int __fd,
  ) {
    return _close(
      __fd,
    );
  }

  late final _closePtr = _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
    'close',
  );
  late final _close = _closePtr.asFunction<int Function(int)>();

  int read(
    int __fd,
    ffi.Pointer<ffi.Void> __buf,
    int __nbytes,
  ) {
    return _read(
      __fd,
      __buf,
      __nbytes,
    );
  }

  late final _readPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Long Function(ffi.Int, ffi.Pointer<ffi.Void>, ffi.Size)
        >
      >('read');
  late final _read = _readPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Void>, int)>();

  int write(
    int __fd,
    ffi.Pointer<ffi.Void> __buf,
    int __n,
  ) {
    return _write(
      __fd,
      __buf,
      __n,
    );
  }

  late final _writePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Long Function(ffi.Int, ffi.Pointer<ffi.Void>, ffi.Size)
        >
      >('write');
  late final _write = _writePtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Void>, int)>();

  int pipe(
    ffi.Pointer<ffi.Int> __pipedes,
  ) {
    return _pipe(
      __pipedes,
    );
  }

  late final _pipePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Int>)>>(
        'pipe',
      );
  late final _pipe = _pipePtr.asFunction<int Function(ffi.Pointer<ffi.Int>)>();

  int usleep(
    int __useconds,
  ) {
    return _usleep(
      __useconds,
    );
  }

  late final _usleepPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.UnsignedInt)>>('usleep');
  late final _usleep = _usleepPtr.asFunction<int Function(int)>();

  int chdir(
    ffi.Pointer<ffi.Char> __path,
  ) {
    return _chdir(
      __path,
    );
  }

  late final _chdirPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'chdir',
      );
  late final _chdir = _chdirPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  int dup(
    int __fd,
  ) {
    return _dup(
      __fd,
    );
  }

  late final _dupPtr = _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
    'dup',
  );
  late final _dup = _dupPtr.asFunction<int Function(int)>();

  int dup2(
    int __fd,
    int __fd2,
  ) {
    return _dup2(
      __fd,
      __fd2,
    );
  }

  late final _dup2Ptr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('dup2');
  late final _dup2 = _dup2Ptr.asFunction<int Function(int, int)>();

  int fcntlInt(
    int __fd,
    int __cmd,
    int va,
  ) {
    return _fcntlInt(
      __fd,
      __cmd,
      va,
    );
  }

  late final _fcntlIntPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.Int, ffi.VarArgs<(ffi.Int,)>)
        >
      >('fcntl');
  late final _fcntlInt = _fcntlIntPtr.asFunction<int Function(int, int, int)>();

  int openMode(
    ffi.Pointer<ffi.Char> __file,
    int __oflag,
    int va,
  ) {
    return _openMode(
      __file,
      __oflag,
      va,
    );
  }

  late final _openModePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.VarArgs<(ffi.Int,)>,
          )
        >
      >('open');
  late final _openMode = _openModePtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, int, int)>();

  int tcgetattr(
    int __fd,
    ffi.Pointer<termios> __termios_p,
  ) {
    return _tcgetattr(
      __fd,
      __termios_p,
    );
  }

  late final _tcgetattrPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Pointer<termios>)>
      >('tcgetattr');
  late final _tcgetattr = _tcgetattrPtr
      .asFunction<int Function(int, ffi.Pointer<termios>)>();

  int tcsetattr(
    int __fd,
    int __optional_actions,
    ffi.Pointer<termios> __termios_p,
  ) {
    return _tcsetattr(
      __fd,
      __optional_actions,
      __termios_p,
    );
  }

  late final _tcsetattrPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.Int, ffi.Pointer<termios>)
        >
      >('tcsetattr');
  late final _tcsetattr = _tcsetattrPtr
      .asFunction<int Function(int, int, ffi.Pointer<termios>)>();

  int kill(
    int __pid,
    int __sig,
  ) {
    return _kill(
      __pid,
      __sig,
    );
  }

  late final _killPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('kill');
  late final _kill = _killPtr.asFunction<int Function(int, int)>();

  ffi.Pointer<ffi.Char> strerror(
    int __errnum,
  ) {
    return _strerror(
      __errnum,
    );
  }

  late final _strerrorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int)>>(
        'strerror',
      );
  late final _strerror = _strerrorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  int ioctlWinSize(
    int __fd,
    int __request,
    ffi.Pointer<WinSize> va,
  ) {
    return _ioctlWinSize(
      __fd,
      __request,
      va,
    );
  }

  late final _ioctlWinSizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Int,
            ffi.UnsignedLong,
            ffi.VarArgs<(ffi.Pointer<WinSize>,)>,
          )
        >
      >('ioctl');
  late final _ioctlWinSize = _ioctlWinSizePtr
      .asFunction<int Function(int, int, ffi.Pointer<WinSize>)>();

  int ioctlInt(
    int __fd,
    int __request,
    int va,
  ) {
    return _ioctlInt(
      __fd,
      __request,
      va,
    );
  }

  late final _ioctlIntPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.UnsignedLong, ffi.VarArgs<(ffi.Int,)>)
        >
      >('ioctl');
  late final _ioctlInt = _ioctlIntPtr.asFunction<int Function(int, int, int)>();

  int statvfs(
    ffi.Pointer<ffi.Char> __file,
    ffi.Pointer<Statvfs> __buf,
  ) {
    return _statvfs(
      __file,
      __buf,
    );
  }

  late final _statvfsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<Statvfs>)
        >
      >('statvfs');
  late final _statvfs = _statvfsPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<Statvfs>)>();

  int waitpid(
    int __pid,
    ffi.Pointer<ffi.Int> __stat_loc,
    int __options,
  ) {
    return _waitpid(
      __pid,
      __stat_loc,
      __options,
    );
  }

  late final _waitpidPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Int>, ffi.Int)
        >
      >('waitpid');
  late final _waitpid = _waitpidPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Int>, int)>();

  int sysinfo(
    ffi.Pointer<SysInfo> __info,
  ) {
    return _sysinfo(
      __info,
    );
  }

  late final _sysinfoPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<SysInfo>)>>(
        'sysinfo',
      );
  late final _sysinfo = _sysinfoPtr
      .asFunction<int Function(ffi.Pointer<SysInfo>)>();
}

final class sched_param extends ffi.Struct {
  @ffi.Int()
  external int sched_priority;
}

final class sigset_t_struct extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<ffi.UnsignedLong> __val;
}

typedef sigset_t = sigset_t_struct;

final class posix_spawnattr_t extends ffi.Struct {
  @ffi.Short()
  external int __flags;

  @ffi.Int()
  external int __pgrp;

  external sigset_t __sd;

  external sigset_t __ss;

  external sched_param __sp;

  @ffi.Int()
  external int __policy;

  @ffi.Int()
  external int __cgroup;

  @ffi.Array.multi([15])
  external ffi.Array<ffi.Int> __pad;
}

final class __spawn_action extends ffi.Opaque {}

final class posix_spawn_file_actions_t extends ffi.Struct {
  @ffi.Int()
  external int __allocated;

  @ffi.Int()
  external int __used;

  external ffi.Pointer<__spawn_action> __actions;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Int> __pad;
}

final class UnnamedUnion1 extends ffi.Union {
  @ffi.UnsignedInt()
  external int __ispeed;

  @ffi.UnsignedInt()
  external int c_ispeed;
}

final class UnnamedUnion2 extends ffi.Union {
  @ffi.UnsignedInt()
  external int __ospeed;

  @ffi.UnsignedInt()
  external int c_ospeed;
}

final class termios extends ffi.Struct {
  @ffi.UnsignedInt()
  external int c_iflag;

  @ffi.UnsignedInt()
  external int c_oflag;

  @ffi.UnsignedInt()
  external int c_cflag;

  @ffi.UnsignedInt()
  external int c_lflag;

  @ffi.UnsignedChar()
  external int c_line;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.UnsignedChar> c_cc;

  external UnnamedUnion1 unnamed;

  external UnnamedUnion2 unnamed$1;
}

final class sigval extends ffi.Union {
  @ffi.Int()
  external int sival_int;

  external ffi.Pointer<ffi.Void> sival_ptr;
}

final class UnnamedStruct2 extends ffi.Struct {
  @ffi.Int()
  external int si_pid;

  @ffi.UnsignedInt()
  external int si_uid;
}

final class UnnamedStruct3 extends ffi.Struct {
  @ffi.Int()
  external int si_tid;

  @ffi.Int()
  external int si_overrun;

  external sigval si_sigval;
}

final class UnnamedStruct4 extends ffi.Struct {
  @ffi.Int()
  external int si_pid;

  @ffi.UnsignedInt()
  external int si_uid;

  external sigval si_sigval;
}

final class UnnamedStruct5 extends ffi.Struct {
  @ffi.Int()
  external int si_pid;

  @ffi.UnsignedInt()
  external int si_uid;

  @ffi.Int()
  external int si_status;

  @ffi.Long()
  external int si_utime;

  @ffi.Long()
  external int si_stime;
}

final class UnnamedStruct7 extends ffi.Struct {
  external ffi.Pointer<ffi.Void> _lower;

  external ffi.Pointer<ffi.Void> _upper;
}

final class UnnamedUnion4 extends ffi.Union {
  external UnnamedStruct7 _addr_bnd;

  @ffi.UnsignedInt()
  external int _pkey;
}

final class UnnamedStruct6 extends ffi.Struct {
  external ffi.Pointer<ffi.Void> si_addr;

  @ffi.Short()
  external int si_addr_lsb;

  external UnnamedUnion4 _bounds;
}

final class UnnamedStruct8 extends ffi.Struct {
  @ffi.Long()
  external int si_band;

  @ffi.Int()
  external int si_fd;
}

final class UnnamedStruct9 extends ffi.Struct {
  external ffi.Pointer<ffi.Void> _call_addr;

  @ffi.Int()
  external int _syscall;

  @ffi.UnsignedInt()
  external int _arch;
}

final class UnnamedUnion3 extends ffi.Union {
  @ffi.Array.multi([28])
  external ffi.Array<ffi.Int> _pad;

  external UnnamedStruct2 _kill;

  external UnnamedStruct3 _timer;

  external UnnamedStruct4 _rt;

  external UnnamedStruct5 _sigchld;

  external UnnamedStruct6 _sigfault;

  external UnnamedStruct8 _sigpoll;

  external UnnamedStruct9 _sigsys;
}

final class siginfo_t extends ffi.Struct {
  @ffi.Int()
  external int si_signo;

  @ffi.Int()
  external int si_errno;

  @ffi.Int()
  external int si_code;

  @ffi.Int()
  external int __pad0;

  external UnnamedUnion3 _sifields;
}

final class UnnamedUnion6 extends ffi.Union {
  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>
  sa_handler;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Int, ffi.Pointer<siginfo_t>, ffi.Pointer<ffi.Void>)
    >
  >
  sa_sigaction;
}

final class sigaction extends ffi.Struct {
  external UnnamedUnion6 __sigaction_handler;

  external sigset_t_struct sa_mask;

  @ffi.Int()
  external int sa_flags;

  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> sa_restorer;
}

final class WinSize extends ffi.Struct {
  @ffi.UnsignedShort()
  external int ws_row;

  @ffi.UnsignedShort()
  external int ws_col;

  @ffi.UnsignedShort()
  external int ws_xpixel;

  @ffi.UnsignedShort()
  external int ws_ypixel;
}

final class Statvfs extends ffi.Struct {
  @ffi.UnsignedLong()
  external int f_bsize;

  @ffi.UnsignedLong()
  external int f_frsize;

  @ffi.UnsignedLong()
  external int f_blocks;

  @ffi.UnsignedLong()
  external int f_bfree;

  @ffi.UnsignedLong()
  external int f_bavail;

  @ffi.UnsignedLong()
  external int f_files;

  @ffi.UnsignedLong()
  external int f_ffree;

  @ffi.UnsignedLong()
  external int f_favail;

  @ffi.UnsignedLong()
  external int f_fsid;

  @ffi.UnsignedLong()
  external int f_flag;

  @ffi.UnsignedLong()
  external int f_namemax;

  @ffi.UnsignedInt()
  external int f_type;

  @ffi.Array.multi([5])
  external ffi.Array<ffi.Int> __f_spare;
}

final class SysInfo extends ffi.Opaque {}

const int WNOHANG = 1;

const int O_RDONLY = 0;

const int O_WRONLY = 1;

const int O_RDWR = 2;

const int O_CREAT = 64;

const int O_NOCTTY = 256;

const int O_TRUNC = 512;

const int O_APPEND = 1024;

const int O_NONBLOCK = 2048;

const int F_GETFD = 1;

const int F_SETFD = 2;

const int F_GETFL = 3;

const int F_SETFL = 4;

const int FD_CLOEXEC = 1;

const int VINTR = 0;

const int VQUIT = 1;

const int VERASE = 2;

const int VKILL = 3;

const int VEOF = 4;

const int VTIME = 5;

const int VMIN = 6;

const int VSTART = 8;

const int VSTOP = 9;

const int VSUSP = 10;

const int VEOL = 11;

const int VREPRINT = 12;

const int VDISCARD = 13;

const int VWERASE = 14;

const int VLNEXT = 15;

const int VEOL2 = 16;

const int BRKINT = 2;

const int INPCK = 16;

const int ISTRIP = 32;

const int ICRNL = 256;

const int IXON = 1024;

const int IXANY = 2048;

const int IMAXBEL = 8192;

const int IUTF8 = 16384;

const int OPOST = 1;

const int ONLCR = 4;

const int CS8 = 48;

const int CREAD = 128;

const int HUPCL = 1024;

const int ISIG = 1;

const int ICANON = 2;

const int ECHO = 8;

const int ECHOE = 16;

const int ECHOK = 32;

const int ECHOCTL = 512;

const int ECHOKE = 2048;

const int PENDIN = 16384;

const int IEXTEN = 32768;

const int TCSANOW = 0;

const int TCSAFLUSH = 2;

const int B38400 = 38400;

const int TIOCSCTTY = 21518;

const int TIOCGWINSZ = 21523;

const int TIOCSWINSZ = 21524;
