// ignore_for_file: non_constant_identifier_names
// ignore_for_file: camel_case_types
// ignore_for_file: public_member_api_docs
// ignore_for_file: constant_identifier_names
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: type=lint
//
// GENERATED by ffigen — do not edit by hand.
// See tool/ffigen_macos.yaml to change what's generated.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// POSIX (libc) + Darwin (mach, sysctl) bindings for macOS, generated
/// by ffigen against the Xcode SDK headers.
///
/// Regenerate via `dart run melos run ffigen_posix_macos` after editing
/// this config or after a major SDK bump.
///
class MacosPosixBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  MacosPosixBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  MacosPosixBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int posix_spawn(
    ffi.Pointer<ffi.Int> arg0,
    ffi.Pointer<ffi.Char> arg1,
    ffi.Pointer<posix_spawn_file_actions_t> arg2,
    ffi.Pointer<posix_spawnattr_t> arg3,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __argv,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __envp,
  ) {
    return _posix_spawn(
      arg0,
      arg1,
      arg2,
      arg3,
      __argv,
      __envp,
    );
  }

  late final _posix_spawnPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<posix_spawn_file_actions_t>,
            ffi.Pointer<posix_spawnattr_t>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('posix_spawn');
  late final _posix_spawn = _posix_spawnPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<posix_spawn_file_actions_t>,
          ffi.Pointer<posix_spawnattr_t>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
        )
      >();

  int posix_spawnp(
    ffi.Pointer<ffi.Int> arg0,
    ffi.Pointer<ffi.Char> arg1,
    ffi.Pointer<posix_spawn_file_actions_t> arg2,
    ffi.Pointer<posix_spawnattr_t> arg3,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __argv,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __envp,
  ) {
    return _posix_spawnp(
      arg0,
      arg1,
      arg2,
      arg3,
      __argv,
      __envp,
    );
  }

  late final _posix_spawnpPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<posix_spawn_file_actions_t>,
            ffi.Pointer<posix_spawnattr_t>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('posix_spawnp');
  late final _posix_spawnp = _posix_spawnpPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<posix_spawn_file_actions_t>,
          ffi.Pointer<posix_spawnattr_t>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
        )
      >();

  int posix_spawn_file_actions_addclose(
    ffi.Pointer<posix_spawn_file_actions_t> arg0,
    int arg1,
  ) {
    return _posix_spawn_file_actions_addclose(
      arg0,
      arg1,
    );
  }

  late final _posix_spawn_file_actions_addclosePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<posix_spawn_file_actions_t>, ffi.Int)
        >
      >('posix_spawn_file_actions_addclose');
  late final _posix_spawn_file_actions_addclose =
      _posix_spawn_file_actions_addclosePtr
          .asFunction<
            int Function(ffi.Pointer<posix_spawn_file_actions_t>, int)
          >();

  int posix_spawn_file_actions_adddup2(
    ffi.Pointer<posix_spawn_file_actions_t> arg0,
    int arg1,
    int arg2,
  ) {
    return _posix_spawn_file_actions_adddup2(
      arg0,
      arg1,
      arg2,
    );
  }

  late final _posix_spawn_file_actions_adddup2Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<posix_spawn_file_actions_t>,
            ffi.Int,
            ffi.Int,
          )
        >
      >('posix_spawn_file_actions_adddup2');
  late final _posix_spawn_file_actions_adddup2 =
      _posix_spawn_file_actions_adddup2Ptr
          .asFunction<
            int Function(ffi.Pointer<posix_spawn_file_actions_t>, int, int)
          >();

  int posix_spawn_file_actions_destroy(
    ffi.Pointer<posix_spawn_file_actions_t> arg0,
  ) {
    return _posix_spawn_file_actions_destroy(
      arg0,
    );
  }

  late final _posix_spawn_file_actions_destroyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<posix_spawn_file_actions_t>)
        >
      >('posix_spawn_file_actions_destroy');
  late final _posix_spawn_file_actions_destroy =
      _posix_spawn_file_actions_destroyPtr
          .asFunction<int Function(ffi.Pointer<posix_spawn_file_actions_t>)>();

  int posix_spawn_file_actions_init(
    ffi.Pointer<posix_spawn_file_actions_t> arg0,
  ) {
    return _posix_spawn_file_actions_init(
      arg0,
    );
  }

  late final _posix_spawn_file_actions_initPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<posix_spawn_file_actions_t>)
        >
      >('posix_spawn_file_actions_init');
  late final _posix_spawn_file_actions_init = _posix_spawn_file_actions_initPtr
      .asFunction<int Function(ffi.Pointer<posix_spawn_file_actions_t>)>();

  int posix_spawnattr_destroy(
    ffi.Pointer<posix_spawnattr_t> arg0,
  ) {
    return _posix_spawnattr_destroy(
      arg0,
    );
  }

  late final _posix_spawnattr_destroyPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<posix_spawnattr_t>)>
      >('posix_spawnattr_destroy');
  late final _posix_spawnattr_destroy = _posix_spawnattr_destroyPtr
      .asFunction<int Function(ffi.Pointer<posix_spawnattr_t>)>();

  int posix_spawnattr_init(
    ffi.Pointer<posix_spawnattr_t> arg0,
  ) {
    return _posix_spawnattr_init(
      arg0,
    );
  }

  late final _posix_spawnattr_initPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<posix_spawnattr_t>)>
      >('posix_spawnattr_init');
  late final _posix_spawnattr_init = _posix_spawnattr_initPtr
      .asFunction<int Function(ffi.Pointer<posix_spawnattr_t>)>();

  int waitpid(
    int arg0,
    ffi.Pointer<ffi.Int> arg1,
    int arg2,
  ) {
    return _waitpid(
      arg0,
      arg1,
      arg2,
    );
  }

  late final _waitpidPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Int>, ffi.Int)
        >
      >('waitpid');
  late final _waitpid = _waitpidPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Int>, int)>();

  int grantpt(
    int arg0,
  ) {
    return _grantpt(
      arg0,
    );
  }

  late final _grantptPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>('grantpt');
  late final _grantpt = _grantptPtr.asFunction<int Function(int)>();

  int posix_openpt(
    int arg0,
  ) {
    return _posix_openpt(
      arg0,
    );
  }

  late final _posix_openptPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>('posix_openpt');
  late final _posix_openpt = _posix_openptPtr.asFunction<int Function(int)>();

  ffi.Pointer<ffi.Char> ptsname(
    int arg0,
  ) {
    return _ptsname(
      arg0,
    );
  }

  late final _ptsnamePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int)>>(
        'ptsname',
      );
  late final _ptsname = _ptsnamePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  int unlockpt(
    int arg0,
  ) {
    return _unlockpt(
      arg0,
    );
  }

  late final _unlockptPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>('unlockpt');
  late final _unlockpt = _unlockptPtr.asFunction<int Function(int)>();

  int chdir(
    ffi.Pointer<ffi.Char> arg0,
  ) {
    return _chdir(
      arg0,
    );
  }

  late final _chdirPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'chdir',
      );
  late final _chdir = _chdirPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  int close(
    int arg0,
  ) {
    return _close(
      arg0,
    );
  }

  late final _closePtr = _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
    'close',
  );
  late final _close = _closePtr.asFunction<int Function(int)>();

  int dup(
    int arg0,
  ) {
    return _dup(
      arg0,
    );
  }

  late final _dupPtr = _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
    'dup',
  );
  late final _dup = _dupPtr.asFunction<int Function(int)>();

  int dup2(
    int arg0,
    int arg1,
  ) {
    return _dup2(
      arg0,
      arg1,
    );
  }

  late final _dup2Ptr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('dup2');
  late final _dup2 = _dup2Ptr.asFunction<int Function(int, int)>();

  int pipe(
    ffi.Pointer<ffi.Int> arg0,
  ) {
    return _pipe(
      arg0,
    );
  }

  late final _pipePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Int>)>>(
        'pipe',
      );
  late final _pipe = _pipePtr.asFunction<int Function(ffi.Pointer<ffi.Int>)>();

  int read(
    int arg0,
    ffi.Pointer<ffi.Void> arg1,
    int __nbyte,
  ) {
    return _read(
      arg0,
      arg1,
      __nbyte,
    );
  }

  late final _readPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Long Function(ffi.Int, ffi.Pointer<ffi.Void>, ffi.Size)
        >
      >('read');
  late final _read = _readPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Void>, int)>();

  int write(
    int __fd,
    ffi.Pointer<ffi.Void> __buf,
    int __nbyte,
  ) {
    return _write(
      __fd,
      __buf,
      __nbyte,
    );
  }

  late final _writePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Long Function(ffi.Int, ffi.Pointer<ffi.Void>, ffi.Size)
        >
      >('write');
  late final _write = _writePtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Void>, int)>();

  int usleep(
    int arg0,
  ) {
    return _usleep(
      arg0,
    );
  }

  late final _usleepPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.UnsignedInt)>>('usleep');
  late final _usleep = _usleepPtr.asFunction<int Function(int)>();

  int openMode(
    ffi.Pointer<ffi.Char> arg0,
    int arg1,
    int va,
  ) {
    return _openMode(
      arg0,
      arg1,
      va,
    );
  }

  late final _openModePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.VarArgs<(ffi.Int,)>,
          )
        >
      >('open');
  late final _openMode = _openModePtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, int, int)>();

  int fcntlInt(
    int arg0,
    int arg1,
    int va,
  ) {
    return _fcntlInt(
      arg0,
      arg1,
      va,
    );
  }

  late final _fcntlIntPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.Int, ffi.VarArgs<(ffi.Int,)>)
        >
      >('fcntl');
  late final _fcntlInt = _fcntlIntPtr.asFunction<int Function(int, int, int)>();

  int tcgetattr(
    int arg0,
    ffi.Pointer<termios> arg1,
  ) {
    return _tcgetattr(
      arg0,
      arg1,
    );
  }

  late final _tcgetattrPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Pointer<termios>)>
      >('tcgetattr');
  late final _tcgetattr = _tcgetattrPtr
      .asFunction<int Function(int, ffi.Pointer<termios>)>();

  int tcsetattr(
    int arg0,
    int arg1,
    ffi.Pointer<termios> arg2,
  ) {
    return _tcsetattr(
      arg0,
      arg1,
      arg2,
    );
  }

  late final _tcsetattrPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.Int, ffi.Pointer<termios>)
        >
      >('tcsetattr');
  late final _tcsetattr = _tcsetattrPtr
      .asFunction<int Function(int, int, ffi.Pointer<termios>)>();

  int kill(
    int arg0,
    int arg1,
  ) {
    return _kill(
      arg0,
      arg1,
    );
  }

  late final _killPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('kill');
  late final _kill = _killPtr.asFunction<int Function(int, int)>();

  ffi.Pointer<ffi.Char> strerror(
    int __errnum,
  ) {
    return _strerror(
      __errnum,
    );
  }

  late final _strerrorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int)>>(
        'strerror',
      );
  late final _strerror = _strerrorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  int ioctlWinSize(
    int arg0,
    int arg1,
    ffi.Pointer<WinSize> va,
  ) {
    return _ioctlWinSize(
      arg0,
      arg1,
      va,
    );
  }

  late final _ioctlWinSizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Int,
            ffi.UnsignedLong,
            ffi.VarArgs<(ffi.Pointer<WinSize>,)>,
          )
        >
      >('ioctl');
  late final _ioctlWinSize = _ioctlWinSizePtr
      .asFunction<int Function(int, int, ffi.Pointer<WinSize>)>();

  int ioctlInt(
    int arg0,
    int arg1,
    int va,
  ) {
    return _ioctlInt(
      arg0,
      arg1,
      va,
    );
  }

  late final _ioctlIntPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.UnsignedLong, ffi.VarArgs<(ffi.Int,)>)
        >
      >('ioctl');
  late final _ioctlInt = _ioctlIntPtr.asFunction<int Function(int, int, int)>();

  int statvfs(
    ffi.Pointer<ffi.Char> arg0,
    ffi.Pointer<Statvfs> arg1,
  ) {
    return _statvfs(
      arg0,
      arg1,
    );
  }

  late final _statvfsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<Statvfs>)
        >
      >('statvfs');
  late final _statvfs = _statvfsPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<Statvfs>)>();

  int sysctlbyname(
    ffi.Pointer<ffi.Char> arg0,
    ffi.Pointer<ffi.Void> arg1,
    ffi.Pointer<ffi.Size> oldlenp,
    ffi.Pointer<ffi.Void> arg3,
    int newlen,
  ) {
    return _sysctlbyname(
      arg0,
      arg1,
      oldlenp,
      arg3,
      newlen,
    );
  }

  late final _sysctlbynamePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Size>,
            ffi.Pointer<ffi.Void>,
            ffi.Size,
          )
        >
      >('sysctlbyname');
  late final _sysctlbyname = _sysctlbynamePtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Size>,
          ffi.Pointer<ffi.Void>,
          int,
        )
      >();

  int mach_host_self() {
    return _mach_host_self();
  }

  late final _mach_host_selfPtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedInt Function()>>('mach_host_self');
  late final _mach_host_self = _mach_host_selfPtr.asFunction<int Function()>();

  int host_statistics64(
    int host_priv,
    int flavor,
    ffi.Pointer<ffi.Int> host_info64_out,
    ffi.Pointer<ffi.UnsignedInt> host_info64_outCnt,
  ) {
    return _host_statistics64(
      host_priv,
      flavor,
      host_info64_out,
      host_info64_outCnt,
    );
  }

  late final _host_statistics64Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.UnsignedInt,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.UnsignedInt>,
          )
        >
      >('host_statistics64');
  late final _host_statistics64 = _host_statistics64Ptr
      .asFunction<
        int Function(
          int,
          int,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.UnsignedInt>,
        )
      >();
}

typedef sigset_t = ffi.UnsignedInt;
typedef posix_spawnattr_t = ffi.Pointer<ffi.Void>;
typedef posix_spawn_file_actions_t = ffi.Pointer<ffi.Void>;

final class sigval extends ffi.Union {
  @ffi.Int()
  external int sival_int;

  external ffi.Pointer<ffi.Void> sival_ptr;
}

final class __siginfo extends ffi.Struct {
  @ffi.Int()
  external int si_signo;

  @ffi.Int()
  external int si_errno;

  @ffi.Int()
  external int si_code;

  @ffi.Int()
  external int si_pid;

  @ffi.UnsignedInt()
  external int si_uid;

  @ffi.Int()
  external int si_status;

  external ffi.Pointer<ffi.Void> si_addr;

  external sigval si_value;

  @ffi.Long()
  external int si_band;

  @ffi.Array.multi([7])
  external ffi.Array<ffi.UnsignedLong> __pad;
}

final class __sigaction_u extends ffi.Union {
  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>
  __sa_handler;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Int, ffi.Pointer<__siginfo>, ffi.Pointer<ffi.Void>)
    >
  >
  __sa_sigaction;
}

final class sigaction extends ffi.Struct {
  external __sigaction_u __sigaction_u$1;

  @sigset_t()
  external int sa_mask;

  @ffi.Int()
  external int sa_flags;
}

final class termios extends ffi.Struct {
  @ffi.UnsignedLong()
  external int c_iflag;

  @ffi.UnsignedLong()
  external int c_oflag;

  @ffi.UnsignedLong()
  external int c_cflag;

  @ffi.UnsignedLong()
  external int c_lflag;

  @ffi.Array.multi([20])
  external ffi.Array<ffi.UnsignedChar> c_cc;

  @ffi.UnsignedLong()
  external int c_ispeed;

  @ffi.UnsignedLong()
  external int c_ospeed;
}

final class WinSize extends ffi.Struct {
  @ffi.UnsignedShort()
  external int ws_row;

  @ffi.UnsignedShort()
  external int ws_col;

  @ffi.UnsignedShort()
  external int ws_xpixel;

  @ffi.UnsignedShort()
  external int ws_ypixel;
}

final class Statvfs extends ffi.Struct {
  @ffi.UnsignedLong()
  external int f_bsize;

  @ffi.UnsignedLong()
  external int f_frsize;

  @ffi.UnsignedInt()
  external int f_blocks;

  @ffi.UnsignedInt()
  external int f_bfree;

  @ffi.UnsignedInt()
  external int f_bavail;

  @ffi.UnsignedInt()
  external int f_files;

  @ffi.UnsignedInt()
  external int f_ffree;

  @ffi.UnsignedInt()
  external int f_favail;

  @ffi.UnsignedLong()
  external int f_fsid;

  @ffi.UnsignedLong()
  external int f_flag;

  @ffi.UnsignedLong()
  external int f_namemax;
}

final class vm_statistics64 extends ffi.Struct {
  @ffi.UnsignedInt()
  external int free_count;

  @ffi.UnsignedInt()
  external int active_count;

  @ffi.UnsignedInt()
  external int inactive_count;

  @ffi.UnsignedInt()
  external int wire_count;

  @ffi.Uint64()
  external int zero_fill_count;

  @ffi.Uint64()
  external int reactivations;

  @ffi.Uint64()
  external int pageins;

  @ffi.Uint64()
  external int pageouts;

  @ffi.Uint64()
  external int faults;

  @ffi.Uint64()
  external int cow_faults;

  @ffi.Uint64()
  external int lookups;

  @ffi.Uint64()
  external int hits;

  @ffi.Uint64()
  external int purges;

  @ffi.UnsignedInt()
  external int purgeable_count;

  @ffi.UnsignedInt()
  external int speculative_count;

  @ffi.Uint64()
  external int decompressions;

  @ffi.Uint64()
  external int compressions;

  @ffi.Uint64()
  external int swapins;

  @ffi.Uint64()
  external int swapouts;

  @ffi.UnsignedInt()
  external int compressor_page_count;

  @ffi.UnsignedInt()
  external int throttled_count;

  @ffi.UnsignedInt()
  external int external_page_count;

  @ffi.UnsignedInt()
  external int internal_page_count;

  @ffi.Uint64()
  external int total_uncompressed_pages_in_compressor;

  @ffi.Uint64()
  external int swapped_count;
}

const int WNOHANG = 1;

const int O_RDONLY = 0;

const int O_WRONLY = 1;

const int O_RDWR = 2;

const int O_NONBLOCK = 4;

const int O_APPEND = 8;

const int O_CREAT = 512;

const int O_TRUNC = 1024;

const int O_NOCTTY = 131072;

const int F_GETFD = 1;

const int F_SETFD = 2;

const int F_GETFL = 3;

const int F_SETFL = 4;

const int FD_CLOEXEC = 1;

const int VEOF = 0;

const int VEOL = 1;

const int VEOL2 = 2;

const int VERASE = 3;

const int VWERASE = 4;

const int VKILL = 5;

const int VREPRINT = 6;

const int VINTR = 8;

const int VQUIT = 9;

const int VSUSP = 10;

const int VDSUSP = 11;

const int VSTART = 12;

const int VSTOP = 13;

const int VLNEXT = 14;

const int VDISCARD = 15;

const int VMIN = 16;

const int VTIME = 17;

const int VSTATUS = 18;

const int BRKINT = 2;

const int INPCK = 16;

const int ISTRIP = 32;

const int ICRNL = 256;

const int IXON = 512;

const int IXANY = 2048;

const int IMAXBEL = 8192;

const int IUTF8 = 16384;

const int OPOST = 1;

const int ONLCR = 2;

const int CS8 = 768;

const int CREAD = 2048;

const int HUPCL = 16384;

const int ECHOKE = 1;

const int ECHOE = 2;

const int ECHOK = 4;

const int ECHO = 8;

const int ECHOCTL = 64;

const int ISIG = 128;

const int ICANON = 256;

const int IEXTEN = 1024;

const int PENDIN = 536870912;

const int TCSANOW = 0;

const int TCSAFLUSH = 2;

const int B38400 = 38400;

const int TIOCGWINSZ = 1074295912;

const int TIOCSWINSZ = 2148037735;

const int TIOCSCTTY = 536900705;

const int HOST_VM_INFO64 = 4;

const int HOST_VM_INFO64_COUNT = 40;
