// ignore_for_file: non_constant_identifier_names
// ignore_for_file: camel_case_types
// ignore_for_file: public_member_api_docs
// ignore_for_file: constant_identifier_names
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: type=lint
//
// GENERATED by ffigen — do not edit by hand.
// See tool/ffigen_windows.yaml to change what's generated.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Win32 + CRT bindings for Windows x64, generated by ffigen.
///
/// Regenerate via `dart run melos run ffigen_windows` after editing this
/// config.
///
/// PREREQUISITES on the regenerating host:
///   * VS Build Tools with `Microsoft.VisualStudio.Component.VC.Tools.x86.x64`
///     (supplies vcruntime.h / excpt.h, which the SDK headers include but do
///     not ship) and `Microsoft.VisualStudio.Component.Windows11SDK.26100`.
///   * LLVM at `C:\Program Files\LLVM` — ffigen's default libclang location,
///     which is why no `llvm-path` appears below.
///
class WindowsBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  WindowsBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  WindowsBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int get_errno(
    ffi.Pointer<ffi.Int> _Value,
  ) {
    return _get_errno(
      _Value,
    );
  }

  late final _get_errnoPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Int>)>>(
        '_get_errno',
      );
  late final _get_errno = _get_errnoPtr
      .asFunction<int Function(ffi.Pointer<ffi.Int>)>();

  int strerror_s(
    ffi.Pointer<ffi.Char> _Buffer,
    int _SizeInBytes,
    int _ErrorNumber,
  ) {
    return _strerror_s(
      _Buffer,
      _SizeInBytes,
      _ErrorNumber,
    );
  }

  late final _strerror_sPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Size, ffi.Int)
        >
      >('strerror_s');
  late final _strerror_s = _strerror_sPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, int, int)>();

  HANDLE GetStdHandle(
    int nStdHandle,
  ) {
    return _GetStdHandle(
      nStdHandle,
    );
  }

  late final _GetStdHandlePtr =
      _lookup<ffi.NativeFunction<HANDLE Function(ffi.UnsignedLong)>>(
        'GetStdHandle',
      );
  late final _GetStdHandle =
      _GetStdHandlePtr.asFunction<HANDLE Function(int)>();

  int SetStdHandle(
    int nStdHandle,
    HANDLE hHandle,
  ) {
    return _SetStdHandle(
      nStdHandle,
      hHandle,
    );
  }

  late final _SetStdHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.UnsignedLong, HANDLE)>>(
        'SetStdHandle',
      );
  late final _SetStdHandle =
      _SetStdHandlePtr.asFunction<int Function(int, HANDLE)>();

  HANDLE CreateFileW(
    ffi.Pointer<ffi.WChar> lpFileName,
    int dwDesiredAccess,
    int dwShareMode,
    ffi.Pointer<SECURITY_ATTRIBUTES> lpSecurityAttributes,
    int dwCreationDisposition,
    int dwFlagsAndAttributes,
    HANDLE hTemplateFile,
  ) {
    return _CreateFileW(
      lpFileName,
      dwDesiredAccess,
      dwShareMode,
      lpSecurityAttributes,
      dwCreationDisposition,
      dwFlagsAndAttributes,
      hTemplateFile,
    );
  }

  late final _CreateFileWPtr =
      _lookup<
        ffi.NativeFunction<
          HANDLE Function(
            ffi.Pointer<ffi.WChar>,
            ffi.UnsignedLong,
            ffi.UnsignedLong,
            ffi.Pointer<SECURITY_ATTRIBUTES>,
            ffi.UnsignedLong,
            ffi.UnsignedLong,
            HANDLE,
          )
        >
      >('CreateFileW');
  late final _CreateFileW =
      _CreateFileWPtr.asFunction<
        HANDLE Function(
          ffi.Pointer<ffi.WChar>,
          int,
          int,
          ffi.Pointer<SECURITY_ATTRIBUTES>,
          int,
          int,
          HANDLE,
        )
      >();

  int GetDiskFreeSpaceExW(
    ffi.Pointer<ffi.WChar> lpDirectoryName,
    ffi.Pointer<ULARGE_INTEGER> lpFreeBytesAvailableToCaller,
    ffi.Pointer<ULARGE_INTEGER> lpTotalNumberOfBytes,
    ffi.Pointer<ULARGE_INTEGER> lpTotalNumberOfFreeBytes,
  ) {
    return _GetDiskFreeSpaceExW(
      lpDirectoryName,
      lpFreeBytesAvailableToCaller,
      lpTotalNumberOfBytes,
      lpTotalNumberOfFreeBytes,
    );
  }

  late final _GetDiskFreeSpaceExWPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.WChar>,
            ffi.Pointer<ULARGE_INTEGER>,
            ffi.Pointer<ULARGE_INTEGER>,
            ffi.Pointer<ULARGE_INTEGER>,
          )
        >
      >('GetDiskFreeSpaceExW');
  late final _GetDiskFreeSpaceExW =
      _GetDiskFreeSpaceExWPtr.asFunction<
        int Function(
          ffi.Pointer<ffi.WChar>,
          ffi.Pointer<ULARGE_INTEGER>,
          ffi.Pointer<ULARGE_INTEGER>,
          ffi.Pointer<ULARGE_INTEGER>,
        )
      >();

  int ReadFile(
    HANDLE hFile,
    ffi.Pointer<ffi.Void> lpBuffer,
    int nNumberOfBytesToRead,
    ffi.Pointer<ffi.UnsignedLong> lpNumberOfBytesRead,
    ffi.Pointer<OVERLAPPED> lpOverlapped,
  ) {
    return _ReadFile(
      hFile,
      lpBuffer,
      nNumberOfBytesToRead,
      lpNumberOfBytesRead,
      lpOverlapped,
    );
  }

  late final _ReadFilePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            HANDLE,
            ffi.Pointer<ffi.Void>,
            ffi.UnsignedLong,
            ffi.Pointer<ffi.UnsignedLong>,
            ffi.Pointer<OVERLAPPED>,
          )
        >
      >('ReadFile');
  late final _ReadFile =
      _ReadFilePtr.asFunction<
        int Function(
          HANDLE,
          ffi.Pointer<ffi.Void>,
          int,
          ffi.Pointer<ffi.UnsignedLong>,
          ffi.Pointer<OVERLAPPED>,
        )
      >();

  int WriteFile(
    HANDLE hFile,
    ffi.Pointer<ffi.Void> lpBuffer,
    int nNumberOfBytesToWrite,
    ffi.Pointer<ffi.UnsignedLong> lpNumberOfBytesWritten,
    ffi.Pointer<OVERLAPPED> lpOverlapped,
  ) {
    return _WriteFile(
      hFile,
      lpBuffer,
      nNumberOfBytesToWrite,
      lpNumberOfBytesWritten,
      lpOverlapped,
    );
  }

  late final _WriteFilePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            HANDLE,
            ffi.Pointer<ffi.Void>,
            ffi.UnsignedLong,
            ffi.Pointer<ffi.UnsignedLong>,
            ffi.Pointer<OVERLAPPED>,
          )
        >
      >('WriteFile');
  late final _WriteFile =
      _WriteFilePtr.asFunction<
        int Function(
          HANDLE,
          ffi.Pointer<ffi.Void>,
          int,
          ffi.Pointer<ffi.UnsignedLong>,
          ffi.Pointer<OVERLAPPED>,
        )
      >();

  int CloseHandle(
    HANDLE hObject,
  ) {
    return _CloseHandle(
      hObject,
    );
  }

  late final _CloseHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(HANDLE)>>('CloseHandle');
  late final _CloseHandle = _CloseHandlePtr.asFunction<int Function(HANDLE)>();

  int GetLastError() {
    return _GetLastError();
  }

  late final _GetLastErrorPtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedLong Function()>>('GetLastError');
  late final _GetLastError = _GetLastErrorPtr.asFunction<int Function()>();

  int CreatePipe(
    ffi.Pointer<HANDLE> hReadPipe,
    ffi.Pointer<HANDLE> hWritePipe,
    ffi.Pointer<SECURITY_ATTRIBUTES> lpPipeAttributes,
    int nSize,
  ) {
    return _CreatePipe(
      hReadPipe,
      hWritePipe,
      lpPipeAttributes,
      nSize,
    );
  }

  late final _CreatePipePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<HANDLE>,
            ffi.Pointer<HANDLE>,
            ffi.Pointer<SECURITY_ATTRIBUTES>,
            ffi.UnsignedLong,
          )
        >
      >('CreatePipe');
  late final _CreatePipe =
      _CreatePipePtr.asFunction<
        int Function(
          ffi.Pointer<HANDLE>,
          ffi.Pointer<HANDLE>,
          ffi.Pointer<SECURITY_ATTRIBUTES>,
          int,
        )
      >();

  int WaitForSingleObject(
    HANDLE hHandle,
    int dwMilliseconds,
  ) {
    return _WaitForSingleObject(
      hHandle,
      dwMilliseconds,
    );
  }

  late final _WaitForSingleObjectPtr =
      _lookup<
        ffi.NativeFunction<ffi.UnsignedLong Function(HANDLE, ffi.UnsignedLong)>
      >('WaitForSingleObject');
  late final _WaitForSingleObject =
      _WaitForSingleObjectPtr.asFunction<int Function(HANDLE, int)>();

  int TerminateProcess(
    HANDLE hProcess,
    int uExitCode,
  ) {
    return _TerminateProcess(
      hProcess,
      uExitCode,
    );
  }

  late final _TerminateProcessPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(HANDLE, ffi.UnsignedInt)>>(
        'TerminateProcess',
      );
  late final _TerminateProcess =
      _TerminateProcessPtr.asFunction<int Function(HANDLE, int)>();

  int GetExitCodeProcess(
    HANDLE hProcess,
    ffi.Pointer<ffi.UnsignedLong> lpExitCode,
  ) {
    return _GetExitCodeProcess(
      hProcess,
      lpExitCode,
    );
  }

  late final _GetExitCodeProcessPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(HANDLE, ffi.Pointer<ffi.UnsignedLong>)
        >
      >('GetExitCodeProcess');
  late final _GetExitCodeProcess =
      _GetExitCodeProcessPtr.asFunction<
        int Function(HANDLE, ffi.Pointer<ffi.UnsignedLong>)
      >();

  int CreateProcessW(
    ffi.Pointer<ffi.WChar> lpApplicationName,
    ffi.Pointer<ffi.WChar> lpCommandLine,
    ffi.Pointer<SECURITY_ATTRIBUTES> lpProcessAttributes,
    ffi.Pointer<SECURITY_ATTRIBUTES> lpThreadAttributes,
    int bInheritHandles,
    int dwCreationFlags,
    ffi.Pointer<ffi.Void> lpEnvironment,
    ffi.Pointer<ffi.WChar> lpCurrentDirectory,
    ffi.Pointer<STARTUPINFOW> lpStartupInfo,
    ffi.Pointer<PROCESS_INFORMATION> lpProcessInformation,
  ) {
    return _CreateProcessW(
      lpApplicationName,
      lpCommandLine,
      lpProcessAttributes,
      lpThreadAttributes,
      bInheritHandles,
      dwCreationFlags,
      lpEnvironment,
      lpCurrentDirectory,
      lpStartupInfo,
      lpProcessInformation,
    );
  }

  late final _CreateProcessWPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.WChar>,
            ffi.Pointer<ffi.WChar>,
            ffi.Pointer<SECURITY_ATTRIBUTES>,
            ffi.Pointer<SECURITY_ATTRIBUTES>,
            ffi.Int,
            ffi.UnsignedLong,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.WChar>,
            ffi.Pointer<STARTUPINFOW>,
            ffi.Pointer<PROCESS_INFORMATION>,
          )
        >
      >('CreateProcessW');
  late final _CreateProcessW =
      _CreateProcessWPtr.asFunction<
        int Function(
          ffi.Pointer<ffi.WChar>,
          ffi.Pointer<ffi.WChar>,
          ffi.Pointer<SECURITY_ATTRIBUTES>,
          ffi.Pointer<SECURITY_ATTRIBUTES>,
          int,
          int,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.WChar>,
          ffi.Pointer<STARTUPINFOW>,
          ffi.Pointer<PROCESS_INFORMATION>,
        )
      >();

  int InitializeProcThreadAttributeList(
    ffi.Pointer<PROC_THREAD_ATTRIBUTE_LIST> lpAttributeList,
    int dwAttributeCount,
    int dwFlags,
    ffi.Pointer<ffi.UnsignedLongLong> lpSize,
  ) {
    return _InitializeProcThreadAttributeList(
      lpAttributeList,
      dwAttributeCount,
      dwFlags,
      lpSize,
    );
  }

  late final _InitializeProcThreadAttributeListPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<PROC_THREAD_ATTRIBUTE_LIST>,
            ffi.UnsignedLong,
            ffi.UnsignedLong,
            ffi.Pointer<ffi.UnsignedLongLong>,
          )
        >
      >('InitializeProcThreadAttributeList');
  late final _InitializeProcThreadAttributeList =
      _InitializeProcThreadAttributeListPtr.asFunction<
        int Function(
          ffi.Pointer<PROC_THREAD_ATTRIBUTE_LIST>,
          int,
          int,
          ffi.Pointer<ffi.UnsignedLongLong>,
        )
      >();

  void DeleteProcThreadAttributeList(
    ffi.Pointer<PROC_THREAD_ATTRIBUTE_LIST> lpAttributeList,
  ) {
    return _DeleteProcThreadAttributeList(
      lpAttributeList,
    );
  }

  late final _DeleteProcThreadAttributeListPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<PROC_THREAD_ATTRIBUTE_LIST>)
        >
      >('DeleteProcThreadAttributeList');
  late final _DeleteProcThreadAttributeList =
      _DeleteProcThreadAttributeListPtr.asFunction<
        void Function(ffi.Pointer<PROC_THREAD_ATTRIBUTE_LIST>)
      >();

  int UpdateProcThreadAttribute(
    ffi.Pointer<PROC_THREAD_ATTRIBUTE_LIST> lpAttributeList,
    int dwFlags,
    int Attribute,
    ffi.Pointer<ffi.Void> lpValue,
    int cbSize,
    ffi.Pointer<ffi.Void> lpPreviousValue,
    ffi.Pointer<ffi.UnsignedLongLong> lpReturnSize,
  ) {
    return _UpdateProcThreadAttribute(
      lpAttributeList,
      dwFlags,
      Attribute,
      lpValue,
      cbSize,
      lpPreviousValue,
      lpReturnSize,
    );
  }

  late final _UpdateProcThreadAttributePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<PROC_THREAD_ATTRIBUTE_LIST>,
            ffi.UnsignedLong,
            ffi.UnsignedLongLong,
            ffi.Pointer<ffi.Void>,
            ffi.UnsignedLongLong,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.UnsignedLongLong>,
          )
        >
      >('UpdateProcThreadAttribute');
  late final _UpdateProcThreadAttribute =
      _UpdateProcThreadAttributePtr.asFunction<
        int Function(
          ffi.Pointer<PROC_THREAD_ATTRIBUTE_LIST>,
          int,
          int,
          ffi.Pointer<ffi.Void>,
          int,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.UnsignedLongLong>,
        )
      >();

  int GlobalMemoryStatusEx(
    ffi.Pointer<MEMORYSTATUSEX> lpBuffer,
  ) {
    return _GlobalMemoryStatusEx(
      lpBuffer,
    );
  }

  late final _GlobalMemoryStatusExPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<MEMORYSTATUSEX>)>
      >('GlobalMemoryStatusEx');
  late final _GlobalMemoryStatusEx =
      _GlobalMemoryStatusExPtr.asFunction<
        int Function(ffi.Pointer<MEMORYSTATUSEX>)
      >();

  ffi.Pointer<ffi.Void> FreeSid(
    ffi.Pointer<ffi.Void> pSid,
  ) {
    return _FreeSid(
      pSid,
    );
  }

  late final _FreeSidPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
        >
      >('FreeSid');
  late final _FreeSid =
      _FreeSidPtr.asFunction<
        ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
      >();

  int DeriveCapabilitySidsFromName(
    ffi.Pointer<ffi.WChar> CapName,
    ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Void>>> CapabilityGroupSids,
    ffi.Pointer<ffi.UnsignedLong> CapabilityGroupSidCount,
    ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Void>>> CapabilitySids,
    ffi.Pointer<ffi.UnsignedLong> CapabilitySidCount,
  ) {
    return _DeriveCapabilitySidsFromName(
      CapName,
      CapabilityGroupSids,
      CapabilityGroupSidCount,
      CapabilitySids,
      CapabilitySidCount,
    );
  }

  late final _DeriveCapabilitySidsFromNamePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.WChar>,
            ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Void>>>,
            ffi.Pointer<ffi.UnsignedLong>,
            ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Void>>>,
            ffi.Pointer<ffi.UnsignedLong>,
          )
        >
      >('DeriveCapabilitySidsFromName');
  late final _DeriveCapabilitySidsFromName =
      _DeriveCapabilitySidsFromNamePtr.asFunction<
        int Function(
          ffi.Pointer<ffi.WChar>,
          ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Void>>>,
          ffi.Pointer<ffi.UnsignedLong>,
          ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Void>>>,
          ffi.Pointer<ffi.UnsignedLong>,
        )
      >();

  HANDLE GlobalAlloc(
    int uFlags,
    int dwBytes,
  ) {
    return _GlobalAlloc(
      uFlags,
      dwBytes,
    );
  }

  late final _GlobalAllocPtr =
      _lookup<
        ffi.NativeFunction<
          HANDLE Function(ffi.UnsignedInt, ffi.UnsignedLongLong)
        >
      >('GlobalAlloc');
  late final _GlobalAlloc =
      _GlobalAllocPtr.asFunction<HANDLE Function(int, int)>();

  int GlobalUnlock(
    HANDLE hMem,
  ) {
    return _GlobalUnlock(
      hMem,
    );
  }

  late final _GlobalUnlockPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(HANDLE)>>('GlobalUnlock');
  late final _GlobalUnlock =
      _GlobalUnlockPtr.asFunction<int Function(HANDLE)>();

  ffi.Pointer<ffi.Void> GlobalLock(
    HANDLE hMem,
  ) {
    return _GlobalLock(
      hMem,
    );
  }

  late final _GlobalLockPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(HANDLE)>>(
        'GlobalLock',
      );
  late final _GlobalLock =
      _GlobalLockPtr.asFunction<ffi.Pointer<ffi.Void> Function(HANDLE)>();

  HANDLE GlobalFree(
    HANDLE hMem,
  ) {
    return _GlobalFree(
      hMem,
    );
  }

  late final _GlobalFreePtr =
      _lookup<ffi.NativeFunction<HANDLE Function(HANDLE)>>('GlobalFree');
  late final _GlobalFree = _GlobalFreePtr.asFunction<HANDLE Function(HANDLE)>();

  HANDLE LocalFree(
    HANDLE hMem,
  ) {
    return _LocalFree(
      hMem,
    );
  }

  late final _LocalFreePtr =
      _lookup<ffi.NativeFunction<HANDLE Function(HANDLE)>>('LocalFree');
  late final _LocalFree = _LocalFreePtr.asFunction<HANDLE Function(HANDLE)>();

  int FormatMessageW(
    int dwFlags,
    ffi.Pointer<ffi.Void> lpSource,
    int dwMessageId,
    int dwLanguageId,
    ffi.Pointer<ffi.WChar> lpBuffer,
    int nSize,
    ffi.Pointer<ffi.Pointer<ffi.Char>> Arguments,
  ) {
    return _FormatMessageW(
      dwFlags,
      lpSource,
      dwMessageId,
      dwLanguageId,
      lpBuffer,
      nSize,
      Arguments,
    );
  }

  late final _FormatMessageWPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedLong Function(
            ffi.UnsignedLong,
            ffi.Pointer<ffi.Void>,
            ffi.UnsignedLong,
            ffi.UnsignedLong,
            ffi.Pointer<ffi.WChar>,
            ffi.UnsignedLong,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('FormatMessageW');
  late final _FormatMessageW =
      _FormatMessageWPtr.asFunction<
        int Function(
          int,
          ffi.Pointer<ffi.Void>,
          int,
          int,
          ffi.Pointer<ffi.WChar>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
        )
      >();

  int SetDllDirectoryW(
    ffi.Pointer<ffi.WChar> lpPathName,
  ) {
    return _SetDllDirectoryW(
      lpPathName,
    );
  }

  late final _SetDllDirectoryWPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.WChar>)>>(
        'SetDllDirectoryW',
      );
  late final _SetDllDirectoryW =
      _SetDllDirectoryWPtr.asFunction<int Function(ffi.Pointer<ffi.WChar>)>();

  int CreateHardLinkW(
    ffi.Pointer<ffi.WChar> lpFileName,
    ffi.Pointer<ffi.WChar> lpExistingFileName,
    ffi.Pointer<SECURITY_ATTRIBUTES> lpSecurityAttributes,
  ) {
    return _CreateHardLinkW(
      lpFileName,
      lpExistingFileName,
      lpSecurityAttributes,
    );
  }

  late final _CreateHardLinkWPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.WChar>,
            ffi.Pointer<ffi.WChar>,
            ffi.Pointer<SECURITY_ATTRIBUTES>,
          )
        >
      >('CreateHardLinkW');
  late final _CreateHardLinkW =
      _CreateHardLinkWPtr.asFunction<
        int Function(
          ffi.Pointer<ffi.WChar>,
          ffi.Pointer<ffi.WChar>,
          ffi.Pointer<SECURITY_ATTRIBUTES>,
        )
      >();

  int GetActiveProcessorCount(
    int GroupNumber,
  ) {
    return _GetActiveProcessorCount(
      GroupNumber,
    );
  }

  late final _GetActiveProcessorCountPtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedLong Function(ffi.UnsignedShort)>>(
        'GetActiveProcessorCount',
      );
  late final _GetActiveProcessorCount =
      _GetActiveProcessorCountPtr.asFunction<int Function(int)>();

  int OpenClipboard(
    ffi.Pointer<HWND__> hWndNewOwner,
  ) {
    return _OpenClipboard(
      hWndNewOwner,
    );
  }

  late final _OpenClipboardPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<HWND__>)>>(
        'OpenClipboard',
      );
  late final _OpenClipboard =
      _OpenClipboardPtr.asFunction<int Function(ffi.Pointer<HWND__>)>();

  int CloseClipboard() {
    return _CloseClipboard();
  }

  late final _CloseClipboardPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('CloseClipboard');
  late final _CloseClipboard = _CloseClipboardPtr.asFunction<int Function()>();

  HANDLE SetClipboardData(
    int uFormat,
    HANDLE hMem,
  ) {
    return _SetClipboardData(
      uFormat,
      hMem,
    );
  }

  late final _SetClipboardDataPtr =
      _lookup<ffi.NativeFunction<HANDLE Function(ffi.UnsignedInt, HANDLE)>>(
        'SetClipboardData',
      );
  late final _SetClipboardData =
      _SetClipboardDataPtr.asFunction<HANDLE Function(int, HANDLE)>();

  HANDLE GetClipboardData(
    int uFormat,
  ) {
    return _GetClipboardData(
      uFormat,
    );
  }

  late final _GetClipboardDataPtr =
      _lookup<ffi.NativeFunction<HANDLE Function(ffi.UnsignedInt)>>(
        'GetClipboardData',
      );
  late final _GetClipboardData =
      _GetClipboardDataPtr.asFunction<HANDLE Function(int)>();

  int EmptyClipboard() {
    return _EmptyClipboard();
  }

  late final _EmptyClipboardPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('EmptyClipboard');
  late final _EmptyClipboard = _EmptyClipboardPtr.asFunction<int Function()>();

  int GetConsoleMode(
    HANDLE hConsoleHandle,
    ffi.Pointer<ffi.UnsignedLong> lpMode,
  ) {
    return _GetConsoleMode(
      hConsoleHandle,
      lpMode,
    );
  }

  late final _GetConsoleModePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(HANDLE, ffi.Pointer<ffi.UnsignedLong>)
        >
      >('GetConsoleMode');
  late final _GetConsoleMode =
      _GetConsoleModePtr.asFunction<
        int Function(HANDLE, ffi.Pointer<ffi.UnsignedLong>)
      >();

  int SetConsoleMode(
    HANDLE hConsoleHandle,
    int dwMode,
  ) {
    return _SetConsoleMode(
      hConsoleHandle,
      dwMode,
    );
  }

  late final _SetConsoleModePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(HANDLE, ffi.UnsignedLong)>>(
        'SetConsoleMode',
      );
  late final _SetConsoleMode =
      _SetConsoleModePtr.asFunction<int Function(HANDLE, int)>();

  int CreatePseudoConsole(
    COORD size,
    HANDLE hInput,
    HANDLE hOutput,
    int dwFlags,
    ffi.Pointer<HPCON> phPC,
  ) {
    return _CreatePseudoConsole(
      size,
      hInput,
      hOutput,
      dwFlags,
      phPC,
    );
  }

  late final _CreatePseudoConsolePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Long Function(
            COORD,
            HANDLE,
            HANDLE,
            ffi.UnsignedLong,
            ffi.Pointer<HPCON>,
          )
        >
      >('CreatePseudoConsole');
  late final _CreatePseudoConsole =
      _CreatePseudoConsolePtr.asFunction<
        int Function(COORD, HANDLE, HANDLE, int, ffi.Pointer<HPCON>)
      >();

  int ResizePseudoConsole(
    HPCON hPC,
    COORD size,
  ) {
    return _ResizePseudoConsole(
      hPC,
      size,
    );
  }

  late final _ResizePseudoConsolePtr =
      _lookup<ffi.NativeFunction<ffi.Long Function(HPCON, COORD)>>(
        'ResizePseudoConsole',
      );
  late final _ResizePseudoConsole =
      _ResizePseudoConsolePtr.asFunction<int Function(HPCON, COORD)>();

  void ClosePseudoConsole(
    HPCON hPC,
  ) {
    return _ClosePseudoConsole(
      hPC,
    );
  }

  late final _ClosePseudoConsolePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(HPCON)>>(
        'ClosePseudoConsole',
      );
  late final _ClosePseudoConsole =
      _ClosePseudoConsolePtr.asFunction<void Function(HPCON)>();

  int ShellExecuteExW(
    ffi.Pointer<SHELLEXECUTEINFOW> pExecInfo,
  ) {
    return _ShellExecuteExW(
      pExecInfo,
    );
  }

  late final _ShellExecuteExWPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<SHELLEXECUTEINFOW>)>
      >('ShellExecuteExW');
  late final _ShellExecuteExW =
      _ShellExecuteExWPtr.asFunction<
        int Function(ffi.Pointer<SHELLEXECUTEINFOW>)
      >();

  void CoTaskMemFree(
    ffi.Pointer<ffi.Void> pv,
  ) {
    return _CoTaskMemFree(
      pv,
    );
  }

  late final _CoTaskMemFreePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'CoTaskMemFree',
      );
  late final _CoTaskMemFree =
      _CoTaskMemFreePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  int close(
    int _FileHandle,
  ) {
    return _close(
      _FileHandle,
    );
  }

  late final _closePtr = _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
    '_close',
  );
  late final _close = _closePtr.asFunction<int Function(int)>();

  int dup(
    int _FileHandle,
  ) {
    return _dup(
      _FileHandle,
    );
  }

  late final _dupPtr = _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
    '_dup',
  );
  late final _dup = _dupPtr.asFunction<int Function(int)>();

  int dup2(
    int _FileHandleSrc,
    int _FileHandleDst,
  ) {
    return _dup2(
      _FileHandleSrc,
      _FileHandleDst,
    );
  }

  late final _dup2Ptr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('_dup2');
  late final _dup2 = _dup2Ptr.asFunction<int Function(int, int)>();

  int get_osfhandle(
    int _FileHandle,
  ) {
    return _get_osfhandle(
      _FileHandle,
    );
  }

  late final _get_osfhandlePtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Int)>>(
        '_get_osfhandle',
      );
  late final _get_osfhandle = _get_osfhandlePtr.asFunction<int Function(int)>();

  int open_osfhandle(
    int _OSFileHandle,
    int _Flags,
  ) {
    return _open_osfhandle(
      _OSFileHandle,
      _Flags,
    );
  }

  late final _open_osfhandlePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.IntPtr, ffi.Int)>>(
        '_open_osfhandle',
      );
  late final _open_osfhandle = _open_osfhandlePtr
      .asFunction<int Function(int, int)>();

  int read(
    int _FileHandle,
    ffi.Pointer<ffi.Void> _DstBuf,
    int _MaxCharCount,
  ) {
    return _read(
      _FileHandle,
      _DstBuf,
      _MaxCharCount,
    );
  }

  late final _readPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Void>, ffi.UnsignedInt)
        >
      >('_read');
  late final _read = _readPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Void>, int)>();

  int write(
    int _FileHandle,
    ffi.Pointer<ffi.Void> _Buf,
    int _MaxCharCount,
  ) {
    return _write(
      _FileHandle,
      _Buf,
      _MaxCharCount,
    );
  }

  late final _writePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Void>, ffi.UnsignedInt)
        >
      >('_write');
  late final _write = _writePtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Void>, int)>();

  int CreateAppContainerProfile(
    ffi.Pointer<ffi.WChar> pszAppContainerName,
    ffi.Pointer<ffi.WChar> pszDisplayName,
    ffi.Pointer<ffi.WChar> pszDescription,
    ffi.Pointer<SID_AND_ATTRIBUTES> pCapabilities,
    int dwCapabilityCount,
    ffi.Pointer<ffi.Pointer<ffi.Void>> ppSidAppContainerSid,
  ) {
    return _CreateAppContainerProfile(
      pszAppContainerName,
      pszDisplayName,
      pszDescription,
      pCapabilities,
      dwCapabilityCount,
      ppSidAppContainerSid,
    );
  }

  late final _CreateAppContainerProfilePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Long Function(
            ffi.Pointer<ffi.WChar>,
            ffi.Pointer<ffi.WChar>,
            ffi.Pointer<ffi.WChar>,
            ffi.Pointer<SID_AND_ATTRIBUTES>,
            ffi.UnsignedLong,
            ffi.Pointer<ffi.Pointer<ffi.Void>>,
          )
        >
      >('CreateAppContainerProfile');
  late final _CreateAppContainerProfile =
      _CreateAppContainerProfilePtr.asFunction<
        int Function(
          ffi.Pointer<ffi.WChar>,
          ffi.Pointer<ffi.WChar>,
          ffi.Pointer<ffi.WChar>,
          ffi.Pointer<SID_AND_ATTRIBUTES>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Void>>,
        )
      >();

  int DeleteAppContainerProfile(
    ffi.Pointer<ffi.WChar> pszAppContainerName,
  ) {
    return _DeleteAppContainerProfile(
      pszAppContainerName,
    );
  }

  late final _DeleteAppContainerProfilePtr =
      _lookup<ffi.NativeFunction<ffi.Long Function(ffi.Pointer<ffi.WChar>)>>(
        'DeleteAppContainerProfile',
      );
  late final _DeleteAppContainerProfile =
      _DeleteAppContainerProfilePtr.asFunction<
        int Function(ffi.Pointer<ffi.WChar>)
      >();

  int GetAppContainerFolderPath(
    ffi.Pointer<ffi.WChar> pszAppContainerSid,
    ffi.Pointer<ffi.Pointer<ffi.WChar>> ppszPath,
  ) {
    return _GetAppContainerFolderPath(
      pszAppContainerSid,
      ppszPath,
    );
  }

  late final _GetAppContainerFolderPathPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Long Function(
            ffi.Pointer<ffi.WChar>,
            ffi.Pointer<ffi.Pointer<ffi.WChar>>,
          )
        >
      >('GetAppContainerFolderPath');
  late final _GetAppContainerFolderPath =
      _GetAppContainerFolderPathPtr.asFunction<
        int Function(
          ffi.Pointer<ffi.WChar>,
          ffi.Pointer<ffi.Pointer<ffi.WChar>>,
        )
      >();

  int DeriveAppContainerSidFromAppContainerName(
    ffi.Pointer<ffi.WChar> pszAppContainerName,
    ffi.Pointer<ffi.Pointer<ffi.Void>> ppsidAppContainerSid,
  ) {
    return _DeriveAppContainerSidFromAppContainerName(
      pszAppContainerName,
      ppsidAppContainerSid,
    );
  }

  late final _DeriveAppContainerSidFromAppContainerNamePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Long Function(
            ffi.Pointer<ffi.WChar>,
            ffi.Pointer<ffi.Pointer<ffi.Void>>,
          )
        >
      >('DeriveAppContainerSidFromAppContainerName');
  late final _DeriveAppContainerSidFromAppContainerName =
      _DeriveAppContainerSidFromAppContainerNamePtr.asFunction<
        int Function(ffi.Pointer<ffi.WChar>, ffi.Pointer<ffi.Pointer<ffi.Void>>)
      >();

  int ConvertSidToStringSidW(
    ffi.Pointer<ffi.Void> Sid,
    ffi.Pointer<ffi.Pointer<ffi.WChar>> StringSid,
  ) {
    return _ConvertSidToStringSidW(
      Sid,
      StringSid,
    );
  }

  late final _ConvertSidToStringSidWPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Pointer<ffi.WChar>>,
          )
        >
      >('ConvertSidToStringSidW');
  late final _ConvertSidToStringSidW =
      _ConvertSidToStringSidWPtr.asFunction<
        int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Pointer<ffi.WChar>>)
      >();

  int ConvertStringSidToSidW(
    ffi.Pointer<ffi.WChar> StringSid,
    ffi.Pointer<ffi.Pointer<ffi.Void>> Sid,
  ) {
    return _ConvertStringSidToSidW(
      StringSid,
      Sid,
    );
  }

  late final _ConvertStringSidToSidWPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.WChar>,
            ffi.Pointer<ffi.Pointer<ffi.Void>>,
          )
        >
      >('ConvertStringSidToSidW');
  late final _ConvertStringSidToSidW =
      _ConvertStringSidToSidWPtr.asFunction<
        int Function(ffi.Pointer<ffi.WChar>, ffi.Pointer<ffi.Pointer<ffi.Void>>)
      >();

  int SetEntriesInAclW(
    int cCountOfExplicitEntries,
    ffi.Pointer<EXPLICIT_ACCESS_W> pListOfExplicitEntries,
    ffi.Pointer<ACL> OldAcl,
    ffi.Pointer<ffi.Pointer<ACL>> NewAcl,
  ) {
    return _SetEntriesInAclW(
      cCountOfExplicitEntries,
      pListOfExplicitEntries,
      OldAcl,
      NewAcl,
    );
  }

  late final _SetEntriesInAclWPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedLong Function(
            ffi.UnsignedLong,
            ffi.Pointer<EXPLICIT_ACCESS_W>,
            ffi.Pointer<ACL>,
            ffi.Pointer<ffi.Pointer<ACL>>,
          )
        >
      >('SetEntriesInAclW');
  late final _SetEntriesInAclW =
      _SetEntriesInAclWPtr.asFunction<
        int Function(
          int,
          ffi.Pointer<EXPLICIT_ACCESS_W>,
          ffi.Pointer<ACL>,
          ffi.Pointer<ffi.Pointer<ACL>>,
        )
      >();

  int GetExplicitEntriesFromAclW(
    ffi.Pointer<ACL> pacl,
    ffi.Pointer<ffi.UnsignedLong> pcCountOfExplicitEntries,
    ffi.Pointer<ffi.Pointer<EXPLICIT_ACCESS_W>> pListOfExplicitEntries,
  ) {
    return _GetExplicitEntriesFromAclW(
      pacl,
      pcCountOfExplicitEntries,
      pListOfExplicitEntries,
    );
  }

  late final _GetExplicitEntriesFromAclWPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedLong Function(
            ffi.Pointer<ACL>,
            ffi.Pointer<ffi.UnsignedLong>,
            ffi.Pointer<ffi.Pointer<EXPLICIT_ACCESS_W>>,
          )
        >
      >('GetExplicitEntriesFromAclW');
  late final _GetExplicitEntriesFromAclW =
      _GetExplicitEntriesFromAclWPtr.asFunction<
        int Function(
          ffi.Pointer<ACL>,
          ffi.Pointer<ffi.UnsignedLong>,
          ffi.Pointer<ffi.Pointer<EXPLICIT_ACCESS_W>>,
        )
      >();

  int GetNamedSecurityInfoW(
    ffi.Pointer<ffi.WChar> pObjectName,
    SE_OBJECT_TYPE ObjectType,
    int SecurityInfo,
    ffi.Pointer<ffi.Pointer<ffi.Void>> ppsidOwner,
    ffi.Pointer<ffi.Pointer<ffi.Void>> ppsidGroup,
    ffi.Pointer<ffi.Pointer<ACL>> ppDacl,
    ffi.Pointer<ffi.Pointer<ACL>> ppSacl,
    ffi.Pointer<ffi.Pointer<ffi.Void>> ppSecurityDescriptor,
  ) {
    return _GetNamedSecurityInfoW(
      pObjectName,
      ObjectType.value,
      SecurityInfo,
      ppsidOwner,
      ppsidGroup,
      ppDacl,
      ppSacl,
      ppSecurityDescriptor,
    );
  }

  late final _GetNamedSecurityInfoWPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedLong Function(
            ffi.Pointer<ffi.WChar>,
            ffi.UnsignedInt,
            ffi.UnsignedLong,
            ffi.Pointer<ffi.Pointer<ffi.Void>>,
            ffi.Pointer<ffi.Pointer<ffi.Void>>,
            ffi.Pointer<ffi.Pointer<ACL>>,
            ffi.Pointer<ffi.Pointer<ACL>>,
            ffi.Pointer<ffi.Pointer<ffi.Void>>,
          )
        >
      >('GetNamedSecurityInfoW');
  late final _GetNamedSecurityInfoW =
      _GetNamedSecurityInfoWPtr.asFunction<
        int Function(
          ffi.Pointer<ffi.WChar>,
          int,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Void>>,
          ffi.Pointer<ffi.Pointer<ffi.Void>>,
          ffi.Pointer<ffi.Pointer<ACL>>,
          ffi.Pointer<ffi.Pointer<ACL>>,
          ffi.Pointer<ffi.Pointer<ffi.Void>>,
        )
      >();

  int SetNamedSecurityInfoW(
    ffi.Pointer<ffi.WChar> pObjectName,
    SE_OBJECT_TYPE ObjectType,
    int SecurityInfo,
    ffi.Pointer<ffi.Void> psidOwner,
    ffi.Pointer<ffi.Void> psidGroup,
    ffi.Pointer<ACL> pDacl,
    ffi.Pointer<ACL> pSacl,
  ) {
    return _SetNamedSecurityInfoW(
      pObjectName,
      ObjectType.value,
      SecurityInfo,
      psidOwner,
      psidGroup,
      pDacl,
      pSacl,
    );
  }

  late final _SetNamedSecurityInfoWPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedLong Function(
            ffi.Pointer<ffi.WChar>,
            ffi.UnsignedInt,
            ffi.UnsignedLong,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ACL>,
            ffi.Pointer<ACL>,
          )
        >
      >('SetNamedSecurityInfoW');
  late final _SetNamedSecurityInfoW =
      _SetNamedSecurityInfoWPtr.asFunction<
        int Function(
          ffi.Pointer<ffi.WChar>,
          int,
          int,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ACL>,
          ffi.Pointer<ACL>,
        )
      >();
}

typedef HANDLE = ffi.Pointer<ffi.Void>;

final class UnnamedStruct4 extends ffi.Struct {
  @ffi.UnsignedLong()
  external int LowPart;

  @ffi.UnsignedLong()
  external int HighPart;
}

final class UnnamedStruct5 extends ffi.Struct {
  @ffi.UnsignedLong()
  external int LowPart;

  @ffi.UnsignedLong()
  external int HighPart;
}

final class ULARGE_INTEGER extends ffi.Union {
  external UnnamedStruct4 unnamed;

  external UnnamedStruct5 u;

  @ffi.UnsignedLongLong()
  external int QuadPart;
}

final class SID_AND_ATTRIBUTES extends ffi.Struct {
  external ffi.Pointer<ffi.Void> Sid;

  @ffi.UnsignedLong()
  external int Attributes;
}

final class ACL extends ffi.Struct {
  @ffi.UnsignedChar()
  external int AclRevision;

  @ffi.UnsignedChar()
  external int Sbz1;

  @ffi.UnsignedShort()
  external int AclSize;

  @ffi.UnsignedShort()
  external int AceCount;

  @ffi.UnsignedShort()
  external int Sbz2;
}

final class SECURITY_CAPABILITIES extends ffi.Struct {
  external ffi.Pointer<ffi.Void> AppContainerSid;

  external ffi.Pointer<SID_AND_ATTRIBUTES> Capabilities;

  @ffi.UnsignedLong()
  external int CapabilityCount;

  @ffi.UnsignedLong()
  external int Reserved;
}

final class HKEY__ extends ffi.Struct {
  @ffi.Int()
  external int unused;
}

final class HINSTANCE__ extends ffi.Struct {
  @ffi.Int()
  external int unused;
}

final class HWND__ extends ffi.Struct {
  @ffi.Int()
  external int unused;
}

final class SECURITY_ATTRIBUTES extends ffi.Struct {
  @ffi.UnsignedLong()
  external int nLength;

  external ffi.Pointer<ffi.Void> lpSecurityDescriptor;

  @ffi.Int()
  external int bInheritHandle;
}

final class UnnamedStruct81 extends ffi.Struct {
  @ffi.UnsignedLong()
  external int Offset;

  @ffi.UnsignedLong()
  external int OffsetHigh;
}

final class UnnamedUnion82 extends ffi.Union {
  external UnnamedStruct81 unnamed;

  external ffi.Pointer<ffi.Void> Pointer;
}

final class OVERLAPPED extends ffi.Struct {
  @ffi.UnsignedLongLong()
  external int Internal;

  @ffi.UnsignedLongLong()
  external int InternalHigh;

  external UnnamedUnion82 unnamed;

  external HANDLE hEvent;
}

final class PROCESS_INFORMATION extends ffi.Struct {
  external HANDLE hProcess;

  external HANDLE hThread;

  @ffi.UnsignedLong()
  external int dwProcessId;

  @ffi.UnsignedLong()
  external int dwThreadId;
}

final class STARTUPINFOW extends ffi.Struct {
  @ffi.UnsignedLong()
  external int cb;

  external ffi.Pointer<ffi.WChar> lpReserved;

  external ffi.Pointer<ffi.WChar> lpDesktop;

  external ffi.Pointer<ffi.WChar> lpTitle;

  @ffi.UnsignedLong()
  external int dwX;

  @ffi.UnsignedLong()
  external int dwY;

  @ffi.UnsignedLong()
  external int dwXSize;

  @ffi.UnsignedLong()
  external int dwYSize;

  @ffi.UnsignedLong()
  external int dwXCountChars;

  @ffi.UnsignedLong()
  external int dwYCountChars;

  @ffi.UnsignedLong()
  external int dwFillAttribute;

  @ffi.UnsignedLong()
  external int dwFlags;

  @ffi.UnsignedShort()
  external int wShowWindow;

  @ffi.UnsignedShort()
  external int cbReserved2;

  external ffi.Pointer<ffi.UnsignedChar> lpReserved2;

  external HANDLE hStdInput;

  external HANDLE hStdOutput;

  external HANDLE hStdError;
}

final class PROC_THREAD_ATTRIBUTE_LIST extends ffi.Opaque {}

final class MEMORYSTATUSEX extends ffi.Struct {
  @ffi.UnsignedLong()
  external int dwLength;

  @ffi.UnsignedLong()
  external int dwMemoryLoad;

  @ffi.UnsignedLongLong()
  external int ullTotalPhys;

  @ffi.UnsignedLongLong()
  external int ullAvailPhys;

  @ffi.UnsignedLongLong()
  external int ullTotalPageFile;

  @ffi.UnsignedLongLong()
  external int ullAvailPageFile;

  @ffi.UnsignedLongLong()
  external int ullTotalVirtual;

  @ffi.UnsignedLongLong()
  external int ullAvailVirtual;

  @ffi.UnsignedLongLong()
  external int ullAvailExtendedVirtual;
}

final class STARTUPINFOEXW extends ffi.Struct {
  external STARTUPINFOW StartupInfo;

  external ffi.Pointer<PROC_THREAD_ATTRIBUTE_LIST> lpAttributeList;
}

final class COORD extends ffi.Struct {
  @ffi.Short()
  external int X;

  @ffi.Short()
  external int Y;
}

typedef HPCON = ffi.Pointer<ffi.Void>;

final class UnnamedUnion138 extends ffi.Union {
  external HANDLE hIcon;

  external HANDLE hMonitor;
}

final class SHELLEXECUTEINFOW extends ffi.Struct {
  @ffi.UnsignedLong()
  external int cbSize;

  @ffi.UnsignedLong()
  external int fMask;

  external ffi.Pointer<HWND__> hwnd;

  external ffi.Pointer<ffi.WChar> lpVerb;

  external ffi.Pointer<ffi.WChar> lpFile;

  external ffi.Pointer<ffi.WChar> lpParameters;

  external ffi.Pointer<ffi.WChar> lpDirectory;

  @ffi.Int()
  external int nShow;

  external ffi.Pointer<HINSTANCE__> hInstApp;

  external ffi.Pointer<ffi.Void> lpIDList;

  external ffi.Pointer<ffi.WChar> lpClass;

  external ffi.Pointer<HKEY__> hkeyClass;

  @ffi.UnsignedLong()
  external int dwHotKey;

  external UnnamedUnion138 unnamed;

  external HANDLE hProcess;
}

enum SE_OBJECT_TYPE {
  SE_UNKNOWN_OBJECT_TYPE(0),
  SE_FILE_OBJECT(1),
  SE_SERVICE(2),
  SE_PRINTER(3),
  SE_REGISTRY_KEY(4),
  SE_LMSHARE(5),
  SE_KERNEL_OBJECT(6),
  SE_WINDOW_OBJECT(7),
  SE_DS_OBJECT(8),
  SE_DS_OBJECT_ALL(9),
  SE_PROVIDER_DEFINED_OBJECT(10),
  SE_WMIGUID_OBJECT(11),
  SE_REGISTRY_WOW64_32KEY(12),
  SE_REGISTRY_WOW64_64KEY(13);

  final int value;
  const SE_OBJECT_TYPE(this.value);

  static SE_OBJECT_TYPE fromValue(int value) => switch (value) {
    0 => SE_UNKNOWN_OBJECT_TYPE,
    1 => SE_FILE_OBJECT,
    2 => SE_SERVICE,
    3 => SE_PRINTER,
    4 => SE_REGISTRY_KEY,
    5 => SE_LMSHARE,
    6 => SE_KERNEL_OBJECT,
    7 => SE_WINDOW_OBJECT,
    8 => SE_DS_OBJECT,
    9 => SE_DS_OBJECT_ALL,
    10 => SE_PROVIDER_DEFINED_OBJECT,
    11 => SE_WMIGUID_OBJECT,
    12 => SE_REGISTRY_WOW64_32KEY,
    13 => SE_REGISTRY_WOW64_64KEY,
    _ => throw ArgumentError('Unknown value for SE_OBJECT_TYPE: $value'),
  };
}

enum TRUSTEE_TYPE {
  TRUSTEE_IS_UNKNOWN(0),
  TRUSTEE_IS_USER(1),
  TRUSTEE_IS_GROUP(2),
  TRUSTEE_IS_DOMAIN(3),
  TRUSTEE_IS_ALIAS(4),
  TRUSTEE_IS_WELL_KNOWN_GROUP(5),
  TRUSTEE_IS_DELETED(6),
  TRUSTEE_IS_INVALID(7),
  TRUSTEE_IS_COMPUTER(8);

  final int value;
  const TRUSTEE_TYPE(this.value);

  static TRUSTEE_TYPE fromValue(int value) => switch (value) {
    0 => TRUSTEE_IS_UNKNOWN,
    1 => TRUSTEE_IS_USER,
    2 => TRUSTEE_IS_GROUP,
    3 => TRUSTEE_IS_DOMAIN,
    4 => TRUSTEE_IS_ALIAS,
    5 => TRUSTEE_IS_WELL_KNOWN_GROUP,
    6 => TRUSTEE_IS_DELETED,
    7 => TRUSTEE_IS_INVALID,
    8 => TRUSTEE_IS_COMPUTER,
    _ => throw ArgumentError('Unknown value for TRUSTEE_TYPE: $value'),
  };
}

enum TRUSTEE_FORM {
  TRUSTEE_IS_SID(0),
  TRUSTEE_IS_NAME(1),
  TRUSTEE_BAD_FORM(2),
  TRUSTEE_IS_OBJECTS_AND_SID(3),
  TRUSTEE_IS_OBJECTS_AND_NAME(4);

  final int value;
  const TRUSTEE_FORM(this.value);

  static TRUSTEE_FORM fromValue(int value) => switch (value) {
    0 => TRUSTEE_IS_SID,
    1 => TRUSTEE_IS_NAME,
    2 => TRUSTEE_BAD_FORM,
    3 => TRUSTEE_IS_OBJECTS_AND_SID,
    4 => TRUSTEE_IS_OBJECTS_AND_NAME,
    _ => throw ArgumentError('Unknown value for TRUSTEE_FORM: $value'),
  };
}

enum MULTIPLE_TRUSTEE_OPERATION {
  NO_MULTIPLE_TRUSTEE(0),
  TRUSTEE_IS_IMPERSONATE(1);

  final int value;
  const MULTIPLE_TRUSTEE_OPERATION(this.value);

  static MULTIPLE_TRUSTEE_OPERATION fromValue(int value) => switch (value) {
    0 => NO_MULTIPLE_TRUSTEE,
    1 => TRUSTEE_IS_IMPERSONATE,
    _ => throw ArgumentError(
      'Unknown value for MULTIPLE_TRUSTEE_OPERATION: $value',
    ),
  };
}

final class TRUSTEE_W extends ffi.Struct {
  external ffi.Pointer<TRUSTEE_W> pMultipleTrustee;

  @ffi.UnsignedInt()
  external int MultipleTrusteeOperationAsInt;

  MULTIPLE_TRUSTEE_OPERATION get MultipleTrusteeOperation =>
      MULTIPLE_TRUSTEE_OPERATION.fromValue(MultipleTrusteeOperationAsInt);

  @ffi.UnsignedInt()
  external int TrusteeFormAsInt;

  TRUSTEE_FORM get TrusteeForm => TRUSTEE_FORM.fromValue(TrusteeFormAsInt);

  @ffi.UnsignedInt()
  external int TrusteeTypeAsInt;

  TRUSTEE_TYPE get TrusteeType => TRUSTEE_TYPE.fromValue(TrusteeTypeAsInt);

  external ffi.Pointer<ffi.WChar> ptstrName;
}

enum ACCESS_MODE {
  NOT_USED_ACCESS(0),
  GRANT_ACCESS(1),
  SET_ACCESS(2),
  DENY_ACCESS(3),
  REVOKE_ACCESS(4),
  SET_AUDIT_SUCCESS(5),
  SET_AUDIT_FAILURE(6);

  final int value;
  const ACCESS_MODE(this.value);

  static ACCESS_MODE fromValue(int value) => switch (value) {
    0 => NOT_USED_ACCESS,
    1 => GRANT_ACCESS,
    2 => SET_ACCESS,
    3 => DENY_ACCESS,
    4 => REVOKE_ACCESS,
    5 => SET_AUDIT_SUCCESS,
    6 => SET_AUDIT_FAILURE,
    _ => throw ArgumentError('Unknown value for ACCESS_MODE: $value'),
  };
}

final class EXPLICIT_ACCESS_W extends ffi.Struct {
  @ffi.UnsignedLong()
  external int grfAccessPermissions;

  @ffi.UnsignedInt()
  external int grfAccessModeAsInt;

  ACCESS_MODE get grfAccessMode => ACCESS_MODE.fromValue(grfAccessModeAsInt);

  @ffi.UnsignedLong()
  external int grfInheritance;

  external TRUSTEE_W Trustee;
}

const int ALL_PROCESSOR_GROUPS = 65535;

const int SYNCHRONIZE = 1048576;

const int GENERIC_READ = 2147483648;

const int GENERIC_WRITE = 1073741824;

const int GENERIC_EXECUTE = 536870912;

const int GENERIC_ALL = 268435456;

const int SE_GROUP_ENABLED = 4;

const int OBJECT_INHERIT_ACE = 1;

const int CONTAINER_INHERIT_ACE = 2;

const int INHERITED_ACE = 16;

const int DACL_SECURITY_INFORMATION = 4;

const int FILE_LIST_DIRECTORY = 1;

const int FILE_TRAVERSE = 32;

const int FILE_SHARE_READ = 1;

const int FILE_SHARE_WRITE = 2;

const int FILE_ATTRIBUTE_NORMAL = 128;

const int CREATE_ALWAYS = 2;

const int OPEN_ALWAYS = 4;

const int GMEM_MOVEABLE = 2;

const int CREATE_UNICODE_ENVIRONMENT = 1024;

const int EXTENDED_STARTUPINFO_PRESENT = 524288;

const int STD_INPUT_HANDLE = 4294967286;

const int STD_OUTPUT_HANDLE = 4294967285;

const int STD_ERROR_HANDLE = 4294967284;

const int INFINITE = 4294967295;

const int FORMAT_MESSAGE_IGNORE_INSERTS = 512;

const int FORMAT_MESSAGE_FROM_SYSTEM = 4096;

const int STARTF_USESTDHANDLES = 256;

const int PROC_THREAD_ATTRIBUTE_NUMBER = 65535;

const int PROC_THREAD_ATTRIBUTE_THREAD = 65536;

const int PROC_THREAD_ATTRIBUTE_INPUT = 131072;

const int PROC_THREAD_ATTRIBUTE_ADDITIVE = 262144;

const int ERROR_ALREADY_EXISTS = 183;

const int ERROR_CANCELLED = 1223;

const int SW_HIDE = 0;

const int CF_UNICODETEXT = 13;

const int ENABLE_PROCESSED_INPUT = 1;

const int ENABLE_LINE_INPUT = 2;

const int ENABLE_ECHO_INPUT = 4;

const int ENABLE_VIRTUAL_TERMINAL_INPUT = 512;

const int ENABLE_VIRTUAL_TERMINAL_PROCESSING = 4;

const int SEE_MASK_NOCLOSEPROCESS = 64;

const int O_RDONLY = 0;

const int O_WRONLY = 1;

const int O_RDWR = 2;

const int O_APPEND = 8;

const int O_TRUNC = 512;

const int O_BINARY = 32768;

const int NO_INHERITANCE = 0;

const int SUB_CONTAINERS_AND_OBJECTS_INHERIT = 3;
